apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://k8s.adaptivenetworklab.org/api/endpoints/1/kubernetes
  name: portainer-cluster-Adaptive-Training
contexts:
- context:
    cluster: portainer-cluster-Adaptive-Training
    user: portainer-sa-user-0332ff83-be60-48eb-a30e-ea86bb000a4e-11
  name: portainer-ctx-Adaptive-Training
current-context: portainer-ctx-Adaptive-Training
kind: Config
preferences: {}
users:
- name: portainer-sa-user-0332ff83-be60-48eb-a30e-ea86bb000a4e-11
  user:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiam9oYW4iLCJyb2xlIjoyLCJzY29wZSI6Imt1YmVjb25maWciLCJmb3JjZUNoYW5nZVBhc3N3b3JkIjpmYWxzZSwiaWF0IjoxNjc2NjA2ODQ1fQ.QxAXu_j0yfcrr_Qx-GLP_zcoPZcOeWj1hPbVqkJ6y7Q
